version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: campuslearn-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    networks:
      - campuslearn-network
    restart: unless-stopped

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: campuslearn-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/campuslearn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - db
    networks:
      - campuslearn-network
    restart: unless-stopped

  # Database Service
  db:
    image: postgres:15-alpine
    container_name: campuslearn-db
    environment:
      - POSTGRES_DB=campuslearn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - campuslearn-network
    ports:
      - "5432:5432"
    restart: unless-stopped

  # PGAdmin (Optional, for database management)
  pgadmin:
    image: dpage/pgadmin4
    container_name: campuslearn-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@campuslearn.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - campuslearn-network
    restart: unless-stopped

# Networks
networks:
  campuslearn-network:
    driver: bridge

# Volumes
volumes:
  postgres_data: